name: rick_and_morty_api
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^6.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^0.13.5
  shared_preferences: ^2.0.17
  internet_connection_checker: ^1.0.0+1
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  intl: ^0.17.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/main_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/noimage.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true
